default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:

development:
  <<: *default
  database: sites_development

test:
  <<: *default
  database: sites_test

production:
  <<: *default
  database: sites_production
  username: sites
  password: <%= ENV['SITES_DATABASE_PASSWORD'] %>
